version: '2'
services:
#  --------------------------------
  zookeeper:
    image: 'bitnami/zookeeper:latest'
    ports:
    - '2181:2181'
    hostname: zookeeper
    environment:
    - ALLOW_ANONYMOUS_LOGIN=yes
  kafka:
   image: 'bitnami/kafka:latest'
   hostname: qkafka
   ports:
    - '9092:9092'
   environment:
    - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
    - ALLOW_PLAINTEXT_LISTENER=yes
   volumes:
    - /home/yaniv/dev/quickstart/kafka-docker-kubernetes/bitnami-kafka/shared:/shared
    - /home/yaniv/dev/quickstart/kafka-docker-kubernetes/bitnami-kafka/shared/server.properties:/opt/bitnami/kafka/conf/server.properties
